# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps-1.10.3.822

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "deps.edn"}}-{{ checksum "modules/metagetta/deps.edn" }}
            - v1-dependencies- # fallback if cache not found

      - run:
          name: Dump tools versions
          command: |
            echo clojure -Sdescribe
            clojure -Sdescribe
            echo java -version
            java -version

      - run:
          name: Bring down Clojure dependencies
          command: |
            clojure -P -M:test:clj-kondo
            cd modules/metagetta
            clojure -P -M:test

      - run:
          name: Lint
          command: ./script/lint

      - run:
          name: Run metagetta unit tests
          command: >
            clojure -M:test
            --reporter documentation
            --plugin kaocha.plugin/profiling
            --plugin kaocha.plugin/junit-xml
            --junit-xml-file target/test-results/metagetta-unit/results.xml
          working_directory: ~/repo/modules/metagetta

      - run:
          name: Run cldoc-analyzer unit tests
          command: >
            clojure -M:test
            --reporter documentation
            --plugin kaocha.plugin/profiling
            --plugin kaocha.plugin/junit-xml
            --junit-xml-file target/test-results/cljdoc-analyzer-unit/results.xml
            unit

      - run:
          name: Run cldoc-analyzer integration tests
          command: >
            clojure -M:test
            --reporter documentation
            --plugin kaocha.plugin/profiling
            --plugin kaocha.plugin/junit-xml
            --junit-xml-file target/test-results/cljdoc-analyzer-integration/results.xml
            --no-capture-output
            integration

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{checksum "deps.edn"}}-{{ checksum "modules/metagetta/deps.edn" }}

      - store_test_results:
          path: modules/metagetta/target/test-results

      - store_test_results:
          path: target/test-results

      - store_artifacts:
          path: modules/metagetta/target/test-results

      - store_artifacts:
          path: target/test-results
